#OBTENER EL TOTAL DE PUNTOS ACUMULADOS EN LA QUINIELA PARA UN USUARIO
DROP FUNCTION GET_USER_TOTAL_POINTS;
CREATE FUNCTION GET_USER_TOTAL_POINTS(userName VARCHAR(45)) RETURNS INT
BEGIN
    DECLARE POINTS INT;

    SELECT -1 INTO POINTS FROM users U WHERE U.username=userName;

  RETURN POINTS;
END;